"""One-line, daily-refreshed 7-day spending summary for the dashboard.

A short natural-language sentence ("You spent Rp 1.2m this week, mostly on
Groceries …") generated by the cheap Gemini Flash-Lite model and cached per user
in ``AppState`` so it costs at most one LLM call per user per day. If the model
is unavailable the deterministic fallback sentence is used instead, so the UI is
never empty.
"""

from __future__ import annotations

import logging
from collections import defaultdict
from datetime import datetime, timedelta
from decimal import Decimal

from sqlalchemy import select
from sqlalchemy.orm import Session

from app.db.models import AppState, Category, Transaction, User
from app.db.session import SessionLocal
from app.services import fx, llm
from app.services.parse import format_number, tz
from app.services.weekly_report import _excluded_category_ids

log = logging.getLogger(__name__)

STATE_KEY = "DAILY_SUMMARY_{user_id}"
WINDOW_DAYS = 7


def _money(currency: str, amount: Decimal) -> str:
    prefix = "Rp " if currency.upper() == "IDR" else f"{currency.upper()} "
    return f"{prefix}{format_number(amount)}"


def _spend(
    db: Session,
    user_id: int,
    start: datetime,
    end: datetime,
    currency: str,
    rates: fx.FxRates,
    excluded: set[int],
) -> tuple[Decimal, dict[str, Decimal]]:
    """Total expense and per-category expense over [start, end), in `currency`."""
    conditions = [
        Transaction.user_id == user_id,
        Transaction.deleted_at.is_(None),
        Transaction.type == "expense",
        Transaction.is_internal.is_(False),
        Transaction.occurred_at >= start,
        Transaction.occurred_at < end,
    ]
    if excluded:
        conditions.append(~Transaction.category_id.in_(excluded))
    rows = db.execute(
        select(Transaction.amount, Transaction.currency, Category.name)
        .join(Category, Category.id == Transaction.category_id)
        .where(*conditions)
    ).all()
    by_category: dict[str, Decimal] = defaultdict(lambda: Decimal("0"))
    total = Decimal("0")
    for amount, source_currency, category_name in rows:
        value = fx.convert(Decimal(amount), source_currency or "IDR", currency, rates)
        by_category[str(category_name)] += value
        total += value
    return total, by_category


def _fallback_text(
    currency: str, total: Decimal, prev_total: Decimal, ranked: list[tuple[str, Decimal]]
) -> str:
    if total <= 0:
        return "No tracked spending in the last 7 days."
    sentence = f"You spent {_money(currency, total)} over the last 7 days"
    if ranked:
        top_name, top_amount = ranked[0]
        sentence += f", most on {top_name} ({_money(currency, top_amount)})"
    if prev_total > 0:
        change = (total - prev_total) / prev_total * 100
        if abs(change) >= 5:
            direction = "up" if change > 0 else "down"
            sentence += f" — {direction} {abs(round(change))}% on the week before"
    return sentence + "."


def build_summary_text(db: Session, user: User, now: datetime | None = None) -> str:
    currency = (user.default_currency or "IDR").upper()
    excluded = _excluded_category_ids(db, user.id)
    rates = fx.get_rates_cached(db)

    local_now = now or datetime.now(tz())
    today_start = local_now.replace(hour=0, minute=0, second=0, microsecond=0)
    end = today_start + timedelta(days=1)  # include all of today
    start = end - timedelta(days=WINDOW_DAYS)
    prev_start = start - timedelta(days=WINDOW_DAYS)

    total, by_category = _spend(db, user.id, start, end, currency, rates, excluded)
    prev_total, _ = _spend(db, user.id, prev_start, start, currency, rates, excluded)
    ranked = sorted(by_category.items(), key=lambda kv: kv[1], reverse=True)

    fallback = _fallback_text(currency, total, prev_total, ranked)
    if total <= 0:
        return fallback

    top_lines = "\n".join(f"- {name}: {_money(currency, amount)}" for name, amount in ranked[:5])
    prompt = (
        "Write ONE short, friendly sentence (max ~24 words) summarising this "
        "person's spending over the last 7 days for a budget dashboard. Use only "
        "the figures below — never invent numbers. Mention the total and the "
        "biggest category; if the change vs the previous 7 days is notable, add a "
        "brief note. Plain text only: no greeting, no emoji, no markdown.\n\n"
        f"Currency: {currency}\n"
        f"Total spent (last 7 days): {_money(currency, total)}\n"
        f"Total spent (previous 7 days): {_money(currency, prev_total)}\n"
        f"Top categories (last 7 days):\n{top_lines}\n"
    )
    try:
        text = llm.call(prompt, json_mode=False).strip()
    except Exception as e:  # noqa: BLE001 — any model/transport failure → fallback
        log.warning("daily summary LLM call failed for user %s: %s", user.id, e)
        return fallback
    text = " ".join(text.split())  # collapse any stray newlines/extra spaces
    return text or fallback


def _store(db: Session, user: User, text: str, now: datetime | None = None) -> dict:
    today = (now or datetime.now(tz())).date().isoformat()
    currency = (user.default_currency or "IDR").upper()
    payload = {"date": today, "currency": currency, "text": text}
    key = STATE_KEY.format(user_id=user.id)
    state = db.get(AppState, key)
    if state is None:
        db.add(AppState(key=key, value=payload))
    else:
        state.value = payload
    db.commit()
    return {"text": text, "generated_on": today}


def get_or_build(db: Session, user: User, now: datetime | None = None) -> dict:
    """Return today's cached summary, building (and caching) it on a cache miss."""
    local_now = now or datetime.now(tz())
    today = local_now.date().isoformat()
    currency = (user.default_currency or "IDR").upper()
    state = db.get(AppState, STATE_KEY.format(user_id=user.id))
    if (
        state is not None
        and isinstance(state.value, dict)
        and state.value.get("date") == today
        and state.value.get("currency") == currency
    ):
        return {"text": state.value.get("text", ""), "generated_on": today}
    return _store(db, user, build_summary_text(db, user, now=local_now), now=local_now)


def refresh_all(db: Session | None = None) -> int:
    """Rebuild and cache every user's summary. Used by the daily scheduler job."""
    own_session = db is None
    if own_session:
        db = SessionLocal()
    count = 0
    try:
        for user in db.query(User).all():
            try:
                _store(db, user, build_summary_text(db, user))
                count += 1
            except Exception as e:  # noqa: BLE001
                db.rollback()
                log.exception("daily summary refresh failed for user %s: %s", user.id, e)
    finally:
        if own_session:
            db.close()
    return count
