"""add is_internal to transactions

Revision ID: 6900ef993023
Revises: 87265c77a504
Create Date: 2026-04-17 06:13:10.040758+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6900ef993023'
down_revision: Union[str, None] = '87265c77a504'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_subcharge_transaction', 'subscription_charges', 'transactions', ['transaction_id'], ['id'], use_alter=True)
    op.add_column('transactions', sa.Column('is_internal', sa.Boolean(), server_default=sa.text('false')))
    op.create_foreign_key('fk_transaction_subcharge', 'transactions', 'subscription_charges', ['subscription_charge_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_transaction_subcharge', 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'is_internal')
    op.drop_constraint('fk_subcharge_transaction', 'subscription_charges', type_='foreignkey')
    # ### end Alembic commands ###
